navikt/familie-felles

http-client/src/main/java/no/nav/familie/http/azure/AccessTokenClient.java
http-client/src/main/java/no/nav/familie/http/azure/AccessTokenDto.java

- opprett det absolutte tidspunktet tokenet utløper
- dette lagres i klientklassen da vi ikke lenger får dette fra endepunktet
(strekker også varigheten til tokenet litt lenger da azure anslagsvis er litt mer stabilt)

 azure/mip: endringer knyttet til manglende "expires_on"

---

kontrakt/src/main/java/no/nav/familie/kontrakt/Ressurs.kt
prosessering/src/main/java/no/nav/familie/prosessering/rest/RestTaskService.kt
prosessering/src/main/java/no/nav/familie/prosessering/rest/TaskController.kt

Skal bruke ressurs på kodeverk-endepunktet i `familie-integrasjoner` og ønsker å ta i bruk dette i stedet for å importere fra ks-sak ( `no.nav.familie.ks.kontrakter.sak.Ressurs`) som gjøres ellers. Hvis ønskelig kan vi oppdatere de i sammen slengen.
Tok en kjap prat med Stig - per nå ingen som bruker det enda, så skal gå fint å endre navn

Generalisere pakkenavn

---

http-client/src/main/java/no/nav/familie/http/azure/AccessTokenDto.java

Holder på å ta i bruk nyeste versjon av **familie-felles** i **familie-integrasjoner**. Etter at feltene i `AccessTokenDto` ble satt private klarer ikke lenger infotrygd-integrasjonen å hente token.

Tilgjengeliggjør henting av accesstoken fra dto

---

http-client/src/main/java/no/nav/familie/http/client/AbstractRestClient.kt

Fordi HttpClientErrorException bør kastes som den er.

Fjernet wrapping i RTE for HttpClientErrorException

---

log/src/main/java/no/nav/familie/log/filter/LogFilter.kt

familie-felles log brukes også av ytelsen omsorgspenger(som er en del av område familie).
Her brukes det en variant til av callId. Legger derfor inn støtte for dette.

Lagt inn støtte for en variant til av CALL_ID

---

sikkerhet/src/main/java/no/nav/familie/sikkerhet/EksternBrukerUtils.kt

OIDCUtil som finnes fra før støtter kun azureAd, denne støtter selvbetjening
Dette er en kopi fra ef-soknad-api men som også nå trengs i ef-mottak

Util metode for å hente fødselsnummer fra jwt token

---

http-client/src/main/java/no/nav/familie/http/config/NaisProxyCustomizer.kt
http-client/src/main/java/no/nav/familie/http/config/RestTemplateBuilderBean.kt
http-client/src/test/java/no/nav/familie/http/config/RestTemplateBuilderBeanTest.kt
http-client/src/test/java/no/nav/familie/http/sts/StsRestClientTest.kt
leader/src/test/kotlin/no/nav/familie/leader/LeaderClientTest.kt

Hvis man ikke setter timeouts httpClient automatisk -1 som verdi, som er ca 15 min timeout.
Vi ønsker att man kaster exception før 15. 
I tillegg så overskrever iNaisProxyCustomizer eventuelle timeouts man setter på RestTemplateBuilder.
Hvis man bruker restTemplateBuilder med timeouts så blir timeouts overskrevne pga`RestTemplateBuilder(iNaisProxyCustomizer)`. Build legger til customisers i sluttet, etter att man har satt timeouts, og overskrever disse.
```kotlin
@Bean
fun operations(restTemplateBuilder: RestTemplateBuilder): RestOperations {
restTemplateBuilder
.setConnectTimeout(Duration.of(30, ChronoUnit.SECONDS)) // blir overskreven av NaisProxyCustomizer
.setReadTimeout(Duration.of(180, ChronoUnit.SECONDS)) // blir overskreven av NaisProxyCustomizer
.build()
}
```
Det hadde nog vært …

Timeouts i restTemplateBuilder blir overskrevne av NaisProxyCustomizer

---

http-client/pom.xml
kafka/pom.xml
leader/pom.xml
log/pom.xml
pom.xml
web-client/pom.xml

Då dette prosjekt likevel er avhengig av spring sine avhengigheter, og alle prosjekt som bruker denne skriver over disse versjonene med egen spring-parent, så er vedlikeholdet enklere hvis vi tar i bruk spring-boot-bom.
Det som skjer nå er att vi får 25 pull requests på hver dependency, som likevel blir overskrevet av applikasjonen som tar i bruk felles

Depedenency-management spring-bom

---

http-client/src/main/java/no/nav/familie/http/ecb/config/ECBRestClientConfig.kt
http-client/src/main/java/no/nav/familie/http/ecb/interceptor/ECBRestClientInterceptor.kt
http-client/src/test/java/no/nav/familie/http/ecb/ECBClientTest.kt

`@Component` på ECBRestClientInterceptor skapte problemer for apper som bruker component scan på hele `familie-felles`. Har derfor fjernet `@Component` og initialiserer ECBRestClientInterceptor direkte inne i RestTemplate configen for ECB.

Fjernet @Component fra ECBRestClientInterceptor

---

.github/workflows/build-deploy.yml
http-client/src/main/java/no/nav/familie/http/client/RetryOAuth2HttpClient.kt
http-client/src/main/java/no/nav/familie/http/interceptor/BearerTokenClientInterceptor.kt
http-client/src/test/java/no/nav/familie/http/client/RetryOAuth2HttpClientTest.kt
http-client/src/test/java/no/nav/familie/http/interceptor/BearerTokenClientCredentialsClientInterceptorTest.kt
http-client/src/test/java/no/nav/familie/http/interceptor/BearerTokenClientInterceptorTest.kt
http-client/src/test/java/no/nav/familie/http/interceptor/BearerTokenOnBehalfOfClientInterceptorTest.kt
log/src/main/java/no/nav/familie/log/filter/RequestTimeFilter.kt
pom.xml
sikkerhet/src/main/java/no/nav/familie/sikkerhet/ClientTokenValidationFilter.kt
sikkerhet/src/main/java/no/nav/familie/sikkerhet/EksternBrukerUtils.kt
sikkerhet/src/main/java/no/nav/familie/sikkerhet/OIDCUtil.kt
web-client/src/main/java/no/nav/familie/webflux/filter/BearerTokenFilter.kt
web-client/src/test/java/no/nav/familie/webflux/filter/BearerTokenFilterTest.kt

Viktigste endringer:
Må bruke RestClient i stedet for RestOperations.
Støtte for token i cookies er fjernet. 
Startet bare med en draft, da dette må testes og koordineres ift omskriving til RestClient

Oppgradering til token-support 4.1.3.

---

pom.xml
tidslinje/pom.xml
tidslinje/src/main/kotlin/no/nav/familie/tidslinje/Periode.kt
tidslinje/src/main/kotlin/no/nav/familie/tidslinje/Tidslinje.kt
tidslinje/src/main/kotlin/no/nav/familie/tidslinje/TidslinjePeriode.kt
tidslinje/src/main/kotlin/no/nav/familie/tidslinje/TidslinjePeriodeMedDato.kt
tidslinje/src/main/kotlin/no/nav/familie/tidslinje/Utils.kt
tidslinje/src/main/kotlin/no/nav/familie/tidslinje/utvidelser/FiltrerTidslinjer.kt
tidslinje/src/main/kotlin/no/nav/familie/tidslinje/utvidelser/KombinerTidslinjer.kt
tidslinje/src/main/kotlin/no/nav/familie/tidslinje/utvidelser/PeriodeUtvidelser.kt
tidslinje/src/main/kotlin/no/nav/familie/tidslinje/utvidelser/TidslinjeUtvidelser.kt
tidslinje/src/test/kotlin/no/nav/familie/tidslinje/PeriodeTest.kt
tidslinje/src/test/kotlin/no/nav/familie/tidslinje/TidslinjePeriodeMedDatoTest.kt
tidslinje/src/test/kotlin/no/nav/familie/tidslinje/utvidelser/KombinerMedTest.kt
tidslinje/src/test/kotlin/no/nav/familie/tidslinje/utvidelser/KombinerTidslinjerTest.kt
tidslinje/src/test/kotlin/no/nav/familie/tidslinje/utvidelser/KonverterTidTest.kt
tidslinje/src/test/kotlin/no/nav/familie/tidslinje/utvidelser/MapOgStripTest.kt
tidslinje/src/test/kotlin/no/nav/familie/tidslinje/utvidelser/OmregningTest.kt
tidslinje/src/test/kotlin/no/nav/familie/tidslinje/utvidelser/SlåSammenLikeTest.kt
tidslinje/src/test/kotlin/no/nav/familie/tidslinje/utvidelser/SnittOgKlippTest.kt
tidslinje/src/test/kotlin/no/nav/familie/tidslinje/utvidelser/TidslinjeEnkelTest.kt
tidslinje/src/test/kotlin/no/nav/familie/tidslinje/utvidelser/TidslinjeHierarkiTest.kt
tidslinje/src/test/kotlin/no/nav/familie/tidslinje/utvidelser/TidslinjeInitTest.kt
tidslinje/src/test/kotlin/no/nav/familie/tidslinje/utvidelser/TidslinjeLengdeTest.kt
tidslinje/src/test/kotlin/no/nav/familie/tidslinje/utvidelser/TidslinjeListeTest.kt
tidslinje/src/test/kotlin/no/nav/familie/tidslinje/utvidelser/TidslinjeNullUndefTest.kt
tidslinje/src/test/kotlin/no/nav/familie/tidslinje/utvidelser/TidslinjePeriodeTest.kt
tidslinje/src/test/kotlin/no/nav/familie/tidslinje/utvidelser/TidslinjeUendlighetTest.kt
tidslinje/src/test/kotlin/no/nav/familie/tidslinje/utvidelser/TilTidslinjePerioderMedLocalDateTest.kt

KS og BA skal på sikt bruke samme bibliotek for tidslinje. Per nå har de begge en intern implementasjon. Dette er første steget for en felles løsning. Legger dermed tidslinje-logikken i familie-felles.

NAV-23269: Legger til tidslinje fra KS sak i familie-felles

---

http-client/src/main/java/no/nav/familie/http/client/AbstractRestClient.kt

Slik at man ikke får en RuntimeException. Avklart med @ma10s

Kast ResourceAccessException tilbake til klient

---

log/src/main/java/no/nav/familie/log/NavSystemtype.kt
log/src/main/java/no/nav/familie/log/filter/LogFilter.kt
log/src/test/java/no/nav/familie/log/filter/LogFilterTest.kt
pom.xml

Fjerner tracking cookie for eksterne brukerflater nå som vi muligens trenger ekstra samtykke for å beholde en slik cookie. Jobben for å kunne skru den av hvis samtykke mangler er mye større enn verdien av å bruke denne cookien for eksterne brukere. 
Vi har fremdeles mulighet for å bruke denne cookien i saksbehandlingsløsninger og integrasjonsapplikasjoner. Innfører dermed en breaking change på `LogFilter`, der man nå må sende inn hvilken systemtype applikasjonen er for å kunne bestemme om tracking cookien skal settes eller ikke.
Når man oppdaterer denne dependencien på appene våre må vi ta stilling til hvilken systemtype vi ønsker å bruke:
- `NavSystemtype.NAV_SAKSBEHANDLINGSSYSTEM` vil fremdeles generere tracking cookie og bruke den i logger.
- `NavSystemtype.NAV_INTEGRASJON` vil ikke …

Fjern tracking cookie for eksterne brukerflater

---

pom.xml

Siden vi i byggescriptet [hardkoder versjonen til 3.x](https://github.com/navikt/familie-felles/blob/main/.github/workflows/build-deploy.yml#L50) gir det ikke mening å oppdatere pom-en slik jeg gjorde. Reverter.

Revert major version bump, versjonen er hardkodet til 3.x uansett

---

leader/src/main/kotlin/no/nav/familie/leader/Environment.kt
leader/src/main/kotlin/no/nav/familie/leader/LeaderClient.kt
leader/src/test/kotlin/no/nav/familie/leader/LeaderClientTest.kt

NAV-23684
Lagt til en retry med delay på isLeader. Ser at sidecaren for leader går ned før appen ved redeploy. Muligens at en retry med delay på maks 3s ikke er nok, men samtidig ønsker man ikke for treg isLeader før den feiler. 
Hvis ikke 3s er nok så tenker jeg man kan fjerne error-loggingen. Siden tjenesten vil returnerer null hvis leader er nede.
Også byttet til den oppdaterte ENV-verdien man skal bruke, siden ELECTOR_PATH er gammel måte.

Lagt til retry med delay på reader for å minske antall alarmer når sidecaren går ned før appen

---

valutakurs-klient/src/main/java/no/nav/familie/valutakurs/ValutakursRestClient.kt
valutakurs-klient/src/test/java/no/nav/familie/valutakurs/ValutakursRestClientTest.kt

Favrokort: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-24455
Fra rundt 08:30 tiden i dag så har vi hatt noe feil når vi prøver å nå ECB.
Dette kan også reproduseres i test.
"melding": "404  on GET request for \"https://data-api.ecb.europa.eu/service/data/EXR/D.NOK+SEK.EUR.SP00.A/\": [no body]",
Når man forsøker dette:
➤ curl https://data-api.ecb.europa.eu/service/data/EXR/D.NOK+PLN.EUR.SP00.A/ så får man 404.
Forsøker man dette
➤ curl https://data-api.ecb.europa.eu/service/data/EXR/D.NOK+PLN.EUR.SP00.A  så funker det.
Har de sluttet å støtte trailing slash?
Uanset hva det er, vi fjerner trailing slash hos oss.

Fjerner trailing slash i ECB url

---

leader/src/main/kotlin/no/nav/familie/leader/LeaderClient.kt

Leader kaster error ofte ved redeploy eller nedskalering fordi leader-endepunktet forsvinner mens den kjører en Scheduled task. Noe som skjer ofte i ba-sak, siden man der har noen jobber som kjører regelmessig over poddene. Dette ser ut til å skje før graceful er mottatt sidene de jobbene nå er satt opp med graceful shutdown. 
Endepunktet kaster null hvis det ikke er et leader-endepunkt tilgjenglig, som betyr det samme som at pod ikke er leader. Så ser det som trygt å skru ned loggnivå.

Juster nede logger for leader

---

tidslinje/src/main/kotlin/no/nav/familie/tidslinje/utvidelser/TidslinjeUtvidelser.kt
tidslinje/src/test/kotlin/no/nav/familie/tidslinje/utvidelser/SnittOgKlippTest.kt

Når fra og med-dato på en tidslinje klippes, blir i noen tilfeller siste periode i tidslinjen kortere enn `INF` (definisjonen på uendelighet). Tidslinjer der fom klippes skal beholde uendelighet. Løser problemet ved å sjekke om tidslinjen er uendelig og at `sluttidspunkt` er større eller lik `kalkulertSluttidspunkt`

Klipping av fom på uendelig tidslinje skal beholde uendelighet

---

valutakurs-klient/README.md
valutakurs-klient/pom.xml
valutakurs-klient/src/main/java/no/nav/familie/valutakurs/ValutakursRestClient.kt
valutakurs-klient/src/main/java/no/nav/familie/valutakurs/config/ValutakursRestClientConfig.kt
valutakurs-klient/src/test/java/no/nav/familie/valutakurs/ValutakursIntegrasjonTest.kt

NAV-24457
Robustgjøring av klienten. 
- Spør etter en spesifikk versjon av kontrakten for at tjenesten ikke skal plutselig endre seg. 
- Lagt til støtte for integrasjonstester og konfigurer Maven-profiler for testkjøring

Robustgjøring av valutakurs

---

tidslinje/src/main/kotlin/no/nav/familie/tidslinje/utvidelser/TidslinjeUtvidelser.kt
tidslinje/src/test/kotlin/no/nav/familie/tidslinje/utvidelser/TidslinjeUtvidelserTest.kt

I metodene `trimVenstre()` og `trimHøyre()` looper vi over alle perioder og identifiserer alle de første eller siste elementene som matcher innsendt `periodeVerdi`. Periodene som matcher forsøker vi å fjerne ved hjelp av `perioder.remove(periode)`, som fjerner første matchende periode fra lista. Dette fungerer for `trimVenstre`, men når vi kjører `trimHøyre` kan man ende opp med å fjerne et element som ikke ligger sist i lista dersom det finnes et element som kommer tidligere i lista som matcher innsendt `periodeVerdi`.
Skriver her om til å bruke henholdsvis `dropWhile` for `trimVenstre` og `dropLastWhile` for `trimHøyre` for å sørge for at vi ikke ender opp med å fjerne andre elementer enn de første og siste som matcher innsendt `periodeVerdi`.

NAV-24606: Fikser bug relatert til hjelpemetoden `trim` for tidslinjer
