navikt/familie-felles

http-client/src/main/java/no/nav/familie/http/sts/StsAccessTokenFeilException.java
http-client/src/main/java/no/nav/familie/http/sts/StsRestClient.java

Kaster exception ved feil

---

http-client/pom.xml
http-client/src/main/java/no/nav/familie/http/azure/AccessTokenClient.java
http-client/src/main/java/no/nav/familie/http/azure/AccessTokenDto.java
http-client/src/main/java/no/nav/familie/http/azure/AccessTokenRequestBody.java
http-client/src/main/java/no/nav/familie/http/azure/AzureAccessTokenException.java
http-client/src/test/java/no/nav/familie/http/client/azure/AzureAccessTokenClientTest.java
pom.xml

Har lagt til RestTemplate her. Tenker det kan være en start på å få rest template inn som client på sikt.

Lager fellestjeneste for å hente azure ad token.

---

http-client/src/main/java/no/nav/familie/http/azure/AccessTokenClient.java

- Dette fordi vi nå går mot Microsoft identity platform (videreføringen av AAD, også kalt '2.0')
- Se https://docs.microsoft.com/en-us/azure/active-directory/develop/

Azuretokenhenting: endre 'resource' til 'scope'

---

sikkerhet/src/main/java/no/nav/familie/sikkerhet/OIDCUtil.java

Om dev profilen er aktiv så prøver vi å hente ut claimet, men returnerer default verdi om det ikke finnes.

Legger til metode for å hente ut et claim.

---

sikkerhet/src/main/java/no/nav/familie/sikkerhet/OIDCUtil.java

... Så kan man hente fagsaker fra ks-sak-frontend lokalt uten å få feil i ks-sak :)

Bruk en dummy NAV-ident når man kjører lokalt

---

prosessering/src/main/java/no/nav/familie/prosessering/domene/Task.kt
prosessering/src/test/java/no/nav/familie/prosessering/task/TaskStep1.kt

- Lag factory method nyTaskMedTriggerTid

---

prosessering/src/main/java/no/nav/familie/prosessering/internal/TaskWorker.kt

Minor change: Bruk findByIdOrNull + error()

Bruk findByIdOrNull in kotlin for å slippe java Optional.

---

prosessering/src/main/java/no/nav/familie/prosessering/domene/TaskLogg.kt
prosessering/src/main/java/no/nav/familie/prosessering/domene/TaskRepository.kt
prosessering/src/main/java/no/nav/familie/prosessering/rest/RestTaskService.kt
prosessering/src/main/java/no/nav/familie/prosessering/rest/TaskController.kt

Støtte for Paging på tasker.
Fiks i response for tasker

Paging på task query

---

sikkerhet/pom.xml
sikkerhet/src/main/java/no/nav/familie/sikkerhet/AuthorizationFilter.kt

Laget filter som gir 401 hvis client id for appen som hentet tokenet ikke er inkludert i accepted clients.

Mini "istio"

---

http-client/src/main/java/no/nav/familie/http/client/AbstractSoapClient.kt
http-client/src/main/java/no/nav/familie/http/health/AbstractHealthIndicator.kt

...og endret konstruktør til å ta inn metrics-navn i stedet for Counter.

Lagt til info-logging av dårlig helse.

---

prosessering/src/main/java/no/nav/familie/prosessering/domene/TaskLogg.kt

Fjerner prepersist og lager timestamp ved opprettelse av objektet.

Tilgjengeliggjør opprettet tidspunkt. 

---

prosessering/src/main/java/no/nav/familie/prosessering/domene/TaskRepository.kt

Lagt til sortering på api brukt i frontend, slik at det blir lettere å finne tasker i familie-prosessering

Sortering på tasker i frontend

---

.github/workflows/build-deploy.yml

Dependabot foreslår å nedgradere versjon nå siden den tror 1. er en nyere versjone enn 1_

Endret versjonering til major punktum istedet for major understrek.

---

sikkerhet/src/main/java/no/nav/familie/sikkerhet/AuthorizationFilter.kt

Legger til mulighet for å disable auth filter.

---

prosessering/src/main/java/no/nav/familie/prosessering/TaskStepBeskrivelse.kt
prosessering/src/main/java/no/nav/familie/prosessering/internal/TaskWorker.kt

Lagt til et nytt felt på annoteringen for å spesifisere neste kjøringstidspunkt for feilet task.

Lagt til støtte for Trigger tid ved feil

---

prosessering/src/main/java/no/nav/familie/prosessering/domene/TaskRepository.kt
prosessering/src/main/java/no/nav/familie/prosessering/rest/RestTaskService.kt
prosessering/src/test/java/no/nav/familie/prosessering/internal/TaskRepositoryTest.kt
prosessering/src/test/java/no/nav/familie/prosessering/rest/TaskControllerIntegrasjonTest.kt
prosessering/src/test/java/no/nav/familie/prosessering/rest/TaskControllerTest.kt

Lagt til max limit på v2 tjenesten av hent tasker.
- Mer tester

Limit på hent alle tasker

---

http-client/src/main/java/no/nav/familie/http/interceptor/BearerTokenWithSTSFallbackClientInterceptor.kt

Skrevet om `BearerTokenWithSTSFallbackClientInterceptor` til å arve fra `BearerTokenClientInterceptor`.

Bearer token interceptor med sts fallback

---

log/src/main/java/no/nav/familie/log/filter/RequestTimeFilter.kt

Denne har tidligere funnits i ef-mottak og ønsker å bruke den i ef-søknad-api også

Flytter RequestTimeFilter fra ef-mottak til felles

---

http-client/pom.xml
http-client/src/main/java/no/nav/familie/http/sts/StsRestClient.kt
http-client/src/test/java/no/nav/familie/http/sts/StsRestClientTest.kt

Fikser feil logikk med expires_in.

StsRestClient hentet alltid nytt token

---

http-client/src/main/java/no/nav/familie/http/sts/StsRestClient.kt

GET-endepunktet i STS er deprekated. Går over til å bruke POST

Bruk POST i STS-restklient

---

prosessering/src/main/java/no/nav/familie/prosessering/rest/RestTaskService.kt
prosessering/src/main/java/no/nav/familie/prosessering/rest/TaskController.kt
prosessering/src/test/java/no/nav/familie/prosessering/rest/TaskControllerTest.kt

https://favro.com/organization/98c34fb974ce445eac854de0/d885c1cd3e763e8a5e124115?card=Tea-1223

Fjerner deprecated versjon av api

---

prosessering/src/main/java/no/nav/familie/prosessering/internal/RekjørSenereException.kt
prosessering/src/main/java/no/nav/familie/prosessering/internal/TaskStepExecutorService.kt
prosessering/src/main/java/no/nav/familie/prosessering/internal/TaskWorker.kt

Kopiert funksjonalitet fra familie-prossessering-backend for å rekjøre senere

Rekjør task senere

---

http-client/src/test/java/no/nav/familie/http/config/RestTemplateBuilderBeanTest.kt
http-client/src/test/java/no/nav/familie/http/sts/StsRestClientTest.kt
leader/pom.xml
pom.xml
prosessering/pom.xml

+ bumper suerfire-plugin så tester også kjører i maven

Fikset tester ved å eksplisitt sette spring-core versjon

---

log/src/main/java/no/nav/familie/log/appender/SecureLoggerRestAppender.kt

Fikser en bug når det finnes en mdc variabel med verdi null kaster NPE ved logging til securelog. Også lagt til generell logging hvis noe går galt i appender. Da blir det skrevet til console.

Forbedringer securelogger over rest. Fikser feil hvor mdc har null verdig og lagt til generell logging ved ukjente feil

---

http-client/src/main/java/no/nav/familie/http/client/AbstractRestClient.kt
log/src/main/java/no/nav/familie/log/appender/SecureLoggerRestAppender.kt

Fjerner logging av manglende eller tomme mdc parametre i securelog
Logging av feil i RestClient til securelogg

Diverse småfikser

---

http-client/src/main/java/no/nav/familie/http/config/NaisProxyCustomizer.kt
web-client/pom.xml
web-client/src/main/java/no/nav/familie/webflux/builder/RestTemplateBuilderBean.kt

nav-token-support trenger en restTemplateBuilder med proxy.

Lagt til restTemplateBuilder med proxy-støtte.

---

http-client/pom.xml
http-client/src/main/java/no/nav/familie/http/client/AbstractRestClient.kt
http-client/src/main/java/no/nav/familie/http/client/RessursException.kt
http-client/src/test/java/no/nav/familie/http/client/AbstractRestClientTest.kt

Etter møte med
@henninghaakonsen @idaame @hensol @stigebil @charliemidtlyng

Prøver å pakke ut ressurs fra feilresponse i AbstractRestClient

---

pom.xml

Erstatter
* https://github.com/navikt/familie-felles/pull/546
* https://github.com/navikt/familie-felles/pull/545
* https://github.com/navikt/familie-felles/pull/542
* https://github.com/navikt/familie-felles/pull/539
* https://github.com/navikt/familie-felles/pull/538
* https://github.com/navikt/familie-felles/pull/505
* https://github.com/navikt/familie-felles/pull/482

Oppdaterer dependabot dependencies

---

http-client/pom.xml
leader/pom.xml
log/pom.xml
log/src/test/java/no/nav/familie/log/filter/AuditLoggerTest.kt
log/src/test/java/no/nav/familie/log/filter/LogFilterTest.kt
pom.xml
web-client/pom.xml

Erstatter kotlin-test-junit med kotlin-test-junit5

Fjerner mockserver-netty, jackson-annotations

---

.github/workflows/build-deploy.yml
http-client/pom.xml
http-client/src/main/java/no/nav/familie/http/client/RetryOAuth2HttpClient.kt
http-client/src/test/java/no/nav/familie/http/interceptor/BearerTokenClientCredentialsClientInterceptorTest.kt
http-client/src/test/java/no/nav/familie/http/interceptor/BearerTokenOnBehalfOfClientInterceptorTest.kt
leader/pom.xml
log/pom.xml
pom.xml
sikkerhet/pom.xml
web-client/pom.xml

Testet i ef-sak lokalt
Token-support kjører på 17, så måtte oppdatere til 17 og

Nav-security til å bruke 2.x som kjører på kotlin (og jdk17)

---

pom.xml

Favro: [Tea-9746](https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-9746)

Tea-9746: Lister opp alle modulane under dependencyManagement, for å i neste runde kunne bruke denne som bill of materials i applikasjonane våre

---

.github/workflows/build-deploy.yml

Samme endring som https://github.com/navikt/familie-prosessering-backend/pull/327

Unngår å bygge nye versjonar viss ein PR blir lukka utan å bli merga, feks for å i neste runde lage ei samle-oppdaterings-pr

---

http-client/src/main/java/no/nav/familie/http/client/AbstractPingableRestClient.kt
http-client/src/main/java/no/nav/familie/http/client/AbstractRestClient.kt

Og setter default null på de andre metodene

Fjerner duplikat av metoder som ikke trengs

---

.github/workflows/build-deploy.yml
sikkerhet/src/main/java/no/nav/familie/sikkerhet/AuthorizationFilter.kt
sikkerhet/src/main/java/no/nav/familie/sikkerhet/EksternBrukerUtils.kt
sikkerhet/src/test/java/no/nav/familie/sikkerhet/EksternBrukerUtilsTest.kt

Legger til idporten som mulig issuer. Lar selvbetjening stå da det skal være bakoverkompatibelt for EF, og fordi BA/KS bruker selvbetjening

Idporten as issuer

---

log/src/main/java/no/nav/familie/log/mdc/MDCUtil.kt

Trekker ut en funksjon fra ba-sak, som jeg har lyst til å bruke flere steder. Gjør at man kan kjøre en funksjon med en valgt callId

Trekker ut overstyrMedCallid til felles

---

util/src/main/kotlin/no/nav/familie/util/VirkedagerProvider.kt
util/src/test/kotlin/no/nav/familie/util/VirkedagerProviderTest.kt

For månedlig valutajustering trenger vi å finne siste virkedag i en måned. Legger til en funksjon for å finne siste virkedag før en dato

Lag en funksjon for å fine seneste virkedag før en dato

---

tidslinje/src/main/kotlin/no/nav/familie/tidslinje/utvidelser/ZipTidslinje.kt
tidslinje/src/test/kotlin/no/nav/familie/tidslinje/utvidelser/ZipTidslinjeTest.kt

Flytter `Tidslinje<V>::zipWithNext` fra ba-sak

Legg til zipWithNext for tidslinje
